version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    deploy:
      resources:
        limits:
          memory: 12G
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - ./data/elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    container_name: kb-container
    deploy:
      resources:
        limits:
          memory: 10G
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  grafana:
    container_name: gf-container
    deploy:
      resources:
        limits:
          memory: 10G
    image: grafana/grafana
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana-data:/var/lib/grafana
networks:
  es-net:
    driver: bridge
